### ISSUE TITLE
Support Interactive Environment

### ISSUE THREAD

**Issue by rlnsanz** [ucbrise/flor#11]
Flor works well once a syntactically-valid python script is available. It works well for the tuning/fitting scenario.

When first composing a pipeline, data scientists will want immediate feedback: line-by-line, as can be provided by iPython or Jupyter notebooks. This enables data scientists to catch bugs early, and better understand the objects they are working with. A data scientist working in this manner will not advance to the next step in the ML pipeline until assured the previous steps "work" (even if they don't provide good results).

Flor needs to support the composition scenario too. Flor should support interactive environments, and the user should be able to move smoothly between interactive and non-interactive environments.

**Comment by rjurney** [comment]
What is required to make this work? Is it mainly inspect stuff?

**Comment by rlnsanz** [comment]
Yes, mainly. We do program analysis, so we need to be able to grab code from Jupyter Cells or ipython. If people put all of their code inside a decorated function, then supporting interactive environments wouldn't be an issue. But people follow a different pattern: people run code in other cells, and expect that state and global variables to be available when they run the next cell (not weird, just hard for us). This requires us to (in the worst case) grab code from every other cell in the Jupyter notebook, and know which cells were run and in what order. 

Moreover, I'm not convinced that asking people to put their code inside a function for Flor to process it is the right interaction for Jupyter Notebooks. People want immediate feedback when they run each cell, they want to see the intermediate state, not just the output of a function. To support this interaction, we'll potential have to instrument Jupyter Notebooks.

**Comment by rlnsanz** [comment]
Added support for Jupyter notebooks. [Here is an example](https://github.com/ucbrise/flor/blob/master/examples/interactive/Basic_Proper.ipynb)

We'll follow up with some documentation
