### ISSUE TITLE
Filename alone is not unique in python. Path is unique. 

### ISSUE THREAD

**Issue by rlnsanz** [ucbrise/flor#29]
https://github.com/ucbrise/flor/blob/2286a9d9774bb69be782ce7a46f3422366f45c08/flor/interface/input/execution_tracker.py#L103

**Comment by louisza** [comment]
Think this is related.

When running the example within a notebook in ipython. I get this error:

`---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-a51c598e1ec6> in <module>
      6 log = flor.log
      7 
----> 8 @flor.track
      9 def fit_and_score_model():
     10     iris = datasets.load_iris()

/opt/conda/lib/python3.6/site-packages/pyflor-0.0.1a0-py3.6.egg/flor/interface/input/execution_tracker.py in track(f)
    103     if filename not in os.listdir(secret_dir):
    104         # Needs compilation
--> 105         with open(tru_path, 'r') as sourcefile:
    106             tree = ast.parse(sourcefile.read())
    107             # logger.debug(astor.dump_tree(tree))

FileNotFoundError: [Errno 2] No such file or directory: '<ipython-input-1-a51c598e1ec6>'`

**Comment by rlnsanz** [comment]
Thank you for the report Louis. This issue is probably due to #11. I'll spend some time over the weekend adding some support for interactive environments. In the meantime, if you'd like to try some of Flor's capabilities you can run your script via `python script.py` (in non-interactive mode). Thanks!
