### ISSUE TITLE
Error when instantiating flor.log

### ISSUE THREAD

**Issue by lpatruno** [ucbrise/flor#34]
Hi. I'm trying to reproduce the iris example from the docs. I've run into an error when installing using `pip3`. Here's the code

```
Luigis-MBP:flor luigi$ docker run --rm -ti python:3.6 bash
root@4587c4a9e79b:/# pip3 install pyflor
Collecting pyflor
  Downloading https://files.pythonhosted.org/packages/59/ca/c90313a0ae1b6d773efb1108b31277d2c605dd16066fd70c63381ae1fc81/pyflor-0.0.1a0-py3-none-any.whl
Installing collected packages: pyflor
Successfully installed pyflor-0.0.1a0
root@4587c4a9e79b:/# python
Python 3.6.8 (default, Feb  6 2019, 12:07:20) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import flor
Coming soon!

>>> flor.log
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'flor' has no attribute 'log'
>>> 
```

When I install from source, I am able to call flor.log.

**Comment by gemengshu** [comment]
Same problem and I install from source lol
The python version is 3.7

**Comment by rlnsanz** [comment]
Thanks everyone, we're rolling out a new version of Flor and the docs are outdated. The new version will be transparent to the user (you won't need to import Flor), but it will require some command-line invocations. I'll follow up once we update the docs, and explain the relevant changes. Leaving the issue open until then.

**Comment by yauhen-info** [comment]
I have the same issue as the topic-starter. Thanks, @rlnsanz, for your work.

Though atm looks like the way described in the [docs](https://flor.readthedocs.io/) is deprecated.

The docs say:
```
from sklearn import datasets
from sklearn import svm
from sklearn.model_selection import train_test_split
import flor

log = flor.log

@flor.track
def fit_and_score_model():
    iris = datasets.load_iris()
    X_tr, X_te, y_tr, y_te = train_test_split(iris.data, iris.target,
                                              test_size=log.param(0.15),
                                              random_state=log.param(430))

    clf = svm.SVC(gamma=log.param(0.001), C=(100.0))
    clf.fit(X_tr, y_tr)

    score = log.metric(clf.score(X_te, y_te))


with flor.Context('iris'):
    fit_and_score_model()
```

The exact same example is under the deprecated folder of the source code https://github.com/ucbrise/flor/blob/master/examples/deprecated/iris/iris.py

Thus, I bet that current working example of Log initialization is under  https://github.com/ucbrise/flor/blob/master/examples/iris/iris.py

**Comment by rlnsanz** [comment]
Hi @yauhen-info, thank you for your interest in Flor and for the feedback. Yes, indeed the docs are deprecated. 

Flor is currently in a state where people should be able to try it on their own machines. I'll spend some time today updating the docs so people can try a tutorial and see what we're about.

Flor is transparent now and invoked from the command line: `flor python iris.py experiment_name_iris`. So you don't need Flor inside your code. More instructions to follow.

**Comment by rlnsanz** [comment]
Hi all, please see updated [docs](http://flor.readthedocs.io). More documentation to follow, but this should be enough to get you started. Thanks!
