### ISSUE TITLE
Error when importing the OpenLog module

### ISSUE THREAD

**Issue by litong-x** [ucbrise/flor#41]
After I installed the newest version successfully, when running the examples in the file iris.py, it raised some error.
```
Traceback (most recent call last):
  File "iris.py", line 4, in <module>
    from flor import OpenLog
ImportError: cannot import name 'OpenLog'
```
I noticed that the newest version just released yesterday, is the module OpenLog done? pls clarify. Thx.

**Comment by rlnsanz** [comment]
Hello and sorry about the confusion. The documentation is currently outdated and we're working to update it. I'll notify you and close this issue as soon as we have a tutorial you can try in the docs.

**Comment by rlnsanz** [comment]
Hello @litong-x , please see updated [docs](https://flor.readthedocs.io/). More documentation to follow, but this should be enough to get you started. Thanks!
