### ISSUE TITLE
[Full Conda ETL] Python programs' control flow inconsistent with our model

### ISSUE THREAD

**Issue by rlnsanz** [ucbrise/flor#43]
The current version of Flor replays executions by scanning Complete Execution Traces (a.k.a logs). 

To succeed, Flor must reconstruct and maintain the stack frame at each log record or program point, which is relevant for modeling name scopes (and other things).   

To track the stack frame at any point in the program, we log function entry / exit points.

Initially, we had a naïve model of Python execution: a function is entered by invocation and exits by reaching a return statement or the end of the block; additionally, the function returns control to the caller. This view overlooked `yield` statements as a means of exiting a function and re-entering them at a point other than the first line in the function body. Moreover, we overlooked `raise` statements as a valid and common means of returning control to an ancestor of the caller --- not just the immediate caller.

In light of these findings, we caught and fixed the bugs in the Flor Scanner (ETL). 

However, after wrapping even more Python libraries (scipy, pandas, etc), we are again witnessing a bug that is similar to the bugs we saw when our execution model misaligned with Python control flow: it is likely that our model of Python Control is incorrect.

The exception reads as follows:

```
(base) ➜  iris_loop git:(master) flor etl bugfx iris_h.py
Traceback (most recent call last):
  File "/anaconda3/envs/flor/bin/pyflor", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/envs/flor/lib/python3.7/site-packages/flor/__main__.py", line 38, in main
    exec_flan(args)
  File "/anaconda3/envs/flor/lib/python3.7/site-packages/flor/commands/flan.py", line 46, in exec_flan
    consolidated_scanner.scan_log()
  File "/anaconda3/envs/flor/lib/python3.7/site-packages/flor/log_scanner/scanner.py", line 123, in scan_log
    self.scan(log_record)
  File "/anaconda3/envs/flor/lib/python3.7/site-packages/flor/log_scanner/scanner.py", line 89, in scan
    log_record['end_function'], ctx.func_ctx)
AssertionError: For log record 48260 ... Expected: getargspec_no_self, Actual: _updated_ctor_param
```

The log record for recreating the bug in the future is available here: [log.json.bz2.zip](https://drive.google.com/open?id=1ZdBk0T5NNkhvjM8O-Z0Ue8ZQ57EWiRJo)

**Comment by rlnsanz** [comment]
A patch in the short-run will be to Flor-Transform only the Scikit-Learn library. This bug does not appear when we generate Complete Execution Traces for Scikit-Learn code. We will have to fix this bug if we want to Flor-Transform all of Anaconda and run ETL on the traces.

**Comment by rlnsanz** [comment]
Possible Solution: write the current stack frame on function exit and immediately on caller resuming control. Instead of reconstructing the stack frame, read it from disk. This approach is more likely to be safe, but could hurt running time.

**Comment by bobbyy98** [comment]
Problem: ```AttributeError: 'ksone_gen' object has no attribute '_ctor_param'```
on line `dct = self._ctor_param.copy()` in `scipy/stats/_distn_infrastructure.py:_updated_ctor_param()`

Possible solution: wrap function in try-catch block and put flor `foot` code in `finally` block.

**Comment by bobbyy98** [comment]
More details:
Flog serialization of instances of the `rv_continuous` class like `ksone_gen`, `kstwobign_gen`, `norm_gen`, `random_correlation_gen` etc. is failing because the attribute `_ctor_param` is accessed by `scipy.stats._distn_infrastructure._updated_ctor_param()`, which is called by `scipy.stats._distn_infrastructure..__getstate__()`, which is called by the flog `serialize` function on line `out = str(cloudpickle.dumps(x))` before the attribute `_ctor_param` is initialized for the `rv_continuous` instances in the transformed `scipy.stats.rv_continuous.__init__()` code:
```
    def __init__(self, momtype=1, a=None, b=None, xtol=1e-14, badvalue=None,
        name=None, longname=None, shapes=None, extradoc=None, seed=None):
        from flor import Flog
        if Flog.flagged(option='nofork'):
            flog = Flog()
        Flog.flagged() and flog.write({'file_path':
            '/Users/bobby/miniconda3/envs/ml/lib/python3.7/site-packages/scipy/stats/_distn_infrastructure.py'
            , 'lsn': 0})
        Flog.flagged() and flog.write({'class_name': 'rv_continuous', 'lsn': 1}
            )
        Flog.flagged() and flog.write({'start_function': '__init__', 'lsn': 2})
        Flog.flagged() and flog.write({'lsn': 3, 'params': [{'0.raw.self':
            flog.serialize(self)}, {'1.raw.momtype': flog.serialize(momtype
            )}, {'2.raw.a': flog.serialize(a)}, {'3.raw.b': flog.serialize(
            b)}, {'4.raw.xtol': flog.serialize(xtol)}, {'5.raw.badvalue':
            flog.serialize(badvalue)}, {'6.raw.name': flog.serialize(name)},
            {'7.raw.longname': flog.serialize(longname)}, {'8.raw.shapes':
            flog.serialize(shapes)}, {'9.raw.extradoc': flog.serialize(
            extradoc)}, {'10.raw.seed': flog.serialize(seed)}]})
        super(rv_continuous, self).__init__(seed)
```
