### ISSUE TITLE
Pytorch warning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead

### ISSUE THREAD

**Issue by eecsliu** [ucbrise/flor#57]
When running any pytorch code, this warning occurs even if the code does not have any calls to `torch.distributed`. Something is happening during/because of flor transformation. This can possible affect execution of a pytorch script; so far only one example has failed me.

**Comment by eecsliu** [comment]
blacklist `__init__` function of `reduce_op` in `distribued_c10d.py`.

**Comment by tebrizli** [comment]
Change the   ___getattribute___   in class __reduce_op_ to this:
    def __getattribute__(self, key):
        if key == "__getattribute__":
            return object.__getattribute__(self, key)
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            return object.__getattribute__(self, key)
